# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protoFormat.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11protoFormat.proto\x12\x05proto\"\x85\x01\n\x0erequestForDaya\x12\r\n\x05RFWID\x18\x01 \x01(\t\x12\x15\n\rbenchmarkType\x18\x02 \x01(\t\x12\x16\n\x0eworkloadMetric\x18\x03 \x01(\t\x12\x11\n\tbatchUnit\x18\x04 \x01(\x05\x12\x0f\n\x07\x62\x61tchID\x18\x05 \x01(\x05\x12\x11\n\tbatchSize\x18\x06 \x01(\x05\"d\n\x0fresponseForData\x12\x0e\n\x06RFWDID\x18\x01 \x01(\t\x12\x13\n\x0bLastBatchID\x18\x02 \x01(\x05\x12\x15\n\rdataRequested\x18\x03 \x03(\x01\x12\x15\n\rdataAnalytics\x18\x04 \x01(\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protoFormat_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUESTFORDAYA._serialized_start=29
  _REQUESTFORDAYA._serialized_end=162
  _RESPONSEFORDATA._serialized_start=164
  _RESPONSEFORDATA._serialized_end=264
# @@protoc_insertion_point(module_scope)
