# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protoFormat.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11protoFormat.proto\"\xa6\x01\n\x0cprotoRequest\x12-\n\x03RFD\x18\x01 \x01(\x0b\x32 .protoRequest.requestForWorkload\x1ag\n\x12requestForWorkload\x12\x0e\n\x06RFWDID\x18\x01 \x01(\t\x12\x13\n\x0bLastBatchID\x18\x02 \x01(\x05\x12\x15\n\rdataRequested\x18\x03 \x03(\x01\x12\x15\n\rdataAnalytics\x18\x04 \x01(\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protoFormat_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PROTOREQUEST._serialized_start=22
  _PROTOREQUEST._serialized_end=188
  _PROTOREQUEST_REQUESTFORWORKLOAD._serialized_start=85
  _PROTOREQUEST_REQUESTFORWORKLOAD._serialized_end=188
# @@protoc_insertion_point(module_scope)
